// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtSsBMQ10H5N-LX7GmJrTOP4KVQAQCQyE',
    appId: '1:470591894560:web:ea629e7e082b3b30627845',
    messagingSenderId: '470591894560',
    projectId: 'recipesuggestion-f8030',
    authDomain: 'recipesuggestion-f8030.firebaseapp.com',
    storageBucket: 'recipesuggestion-f8030.appspot.com',
    measurementId: 'G-V6KDR3R8RE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb0zik1Fh0CLfjV-4GrImffc91ND3_GsY',
    appId: '1:470591894560:android:ef5b56a2bc6c5ada627845',
    messagingSenderId: '470591894560',
    projectId: 'recipesuggestion-f8030',
    storageBucket: 'recipesuggestion-f8030.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC893W0_wby5U3zzJRPA7nukBkTkifr4po',
    appId: '1:470591894560:ios:66568cf0ce0a18af627845',
    messagingSenderId: '470591894560',
    projectId: 'recipesuggestion-f8030',
    storageBucket: 'recipesuggestion-f8030.appspot.com',
    iosBundleId: 'com.example.recipeSuggestion',
  );
}
